language: scala
sudo: false
jdk:
- oraclejdk8
env:
  global:
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_SBT_VERSION="0.13.16"
  - secure: G3Bkh/xrdj1hTiRzO2XqgQCF7MfJH4JmpDRNiIxu/eYtrbhYUB7GvvhSXw1nD3K7Ig19qOCwqJIP6FSQgWKysZAd8ywkINVY5tKH7sbYWiVMBDZD9Qy2Mc5AhQIQnVcAZyW3TVF8iwDfXJsyIEWhUcGvza8h20nngw08RaBUcDIAcUdxM28oM9glCNeTNcc/uv0JaEoDfhQv8YtLOAwyF3ZbGrFZ19JfSGTx+1XDzyXqQ1LfM8PNYRn0xwWZ799aAMuWe+TD0EpXrkyYvYUigz14YaCVcL3At3HQ6tYV2n9gRphaDLnuI7fI5bmeUay4T/Mmy0ikQELeipVDZRjftbZaSweGUUhA/S1paMb/LaVa3ZaCByWifgIqMflxUCnumQGRiV49wG2JRvy3e18yW0hvWAlNS9cmVL59OivAjOlYQbTGpHTAz8pDVzv9eKPd9cz+Cby0PHZAHuArDmSNDrwvg0ue9NOE2JGGazja2M5wpjtOEM8OoTHT8wASoSmE8To7DG+So2AvKeNCP9HTfZFTKbX7lWn4P7h7xdxw+SwinXvz0ehkfEx8Fjz5dBOhD58jqlDlhwUdMC3P7EKRqCHQKesr2sFmsMHQTIwn1bmW8rFbJEzeiA+NldWf3DrIdPnSpWZ6MK1uAuf5hqajQzMKkpfGb4EA1/Yc5IFSqcw=
  - secure: Cyh0+lT4UwA0+8ZphxJlwN5U/7rI4IkJYwkBAQN4AWi5LB9VT3MngfXf0wGEVcAKRdrSlSogY4ROn9aSDzV5H2BQAOOcJmBJ6OyfmQZhdxEyipoG8iXEA00DqeRRSeRczGnjhyvs9uMitBgY84njkjfLX11rvV9ujBxCmwYdOD2O1Y1xuUQXvm+5c1zdUZehlALIzCoU2BcXIM2butfZ8xNUI2L/DlaiwuNLqIJ2TvCHLAochanWwPmXkUexjvbO+2gzIjufUA1sjzBJPI3iC0/zso03jD3XDRj2hthERCsaeH7XiSWfFLwiwWDG79osxaGgZ4Dq9gcLQrYx/3vqYcQkSD1tCAMRZ9dtjpeWDbtdhD7deaniFxFnglYrTzkw9FHqui/LqCBFhilaGOpzvKxTj9r9XHg4t73oFmJBQzGWwzJnIzJd8ejcP4ytZqYbi1JnGZwp77zrZvhG5gPBoEOtCCHsUhksWAzF+AqDcmTLDPD4oY8+TYgOOIbXG1FNAqNzZvZPqFPJZuA3IMVCj0OWPyrGX92yG6TKnHEaDB6Fg22xHqZbSjOqvq9WDqd/1Oo7dnej+C926FwuNz4HIDhVnPylOFv7BpvdTxo/EDTYLMNjVyR2GqgiUrHAUDqVL46DrUeMOcDfzrMOti38yszBRTrwLOnSZovdyG0fq3Q=
before_install:
- nvm install 6
- nvm use 6
- node --version
script:
- sbt clean coverage test coverageReport &&
  sbt coverageAggregate
after_success:
- sbt coveralls
- if [ $TRAVIS_BRANCH = 'master' ] && [[ "$(<version.sbt)" =~ (.*SNAPSHOT.*) ]]; then
    sbt clean publish;
  fi
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
before_cache:
# Cleanup the cached directories to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete
